apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  # For deployment labels are optional
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    # All pods that have the same label are belong to this deployment
    matchLabels:
      app: mongo
  # this is pod template the has label: mongo
  template:
    metadata:
      # for pod the labels are required
      labels:
        app: mongo
    spec:
      containers:
      # this will create pods with mongo:latest image
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources: # this from qwen.ai
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        volumeMounts: # this from qwen.ai
        - name: mongo-storage
          mountPath: /data/db
      volumes: # this from qwen.ai
      - name: mongo-storage
        emptyDir: {}
        
---
apiVersion: v1
kind: Service
metadata:
  # To remember only: this is the name of service that match the mongo-config
  name: mongo-service
spec:
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017