apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  # For deployment labels are optional
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    # All pods that have the same label are belong to this deployment
    matchLabels:
      app: webapp
  # this is pod template the has label: webapp
  template:
    metadata:
      # for pod the labels are required
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      env:
        - name: USERNAME
          valueFrom: 
            # In this way we ref from secret
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            # In this way we ref from map
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000