# version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: