# version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
  test:
    image: jloka_01-backend
    volumes:
      - ./backend:/app
    command: npm test
    depends_on:
      - backend
    environment:
      DB_URL: mongodb://db/vidly
volumes:
  vidly: